import React, { createContext, useContext, useState, useEffect } from 'react';
import { fetchLanguagePreference, saveLanguagePreference } from '../services/themeApi';

export type Language = 'en' | 'zh';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Chinese UI copy — zh mode shows pure Chinese; en mode shows English keys unchanged.
const zhTranslations: Record<string, string> = {
  // Navigation & Sidebar
  "New Chat": "新建会话",
  "New Chat / Reset": "重置",
  "AI Agents": "AI 智能体",
  "Branch": "分支",
  "Not a git repository": "非 Git 仓库",
  "Model": "模型",
  "Engine": "驱动引擎",
  "Model is provided by the selected agent tool": "模型由所选 Agent 工具自带",
  "Workflow": "工作流",
  "System Preferences": "系统设置",
  "Status Overview": "状态概览",
  "Active Preset Themes": "活跃 主题",
  "Available Preset Themes": "可用 主题预设",
  "Workspace:": "工作空间:",
  "Session:": "会话:",
  "ACTIVE": "活跃",
  "STYLING ENGINE OK": "样式引擎正常",
  "REPOSITORIES": "源码仓库",
  "General": "通用",
  "General Settings": "通用设置",
  "Customize your application profile, account settings and default preferences.": "自定义您的应用个人资料、帐户设置和默认偏好。",
  "Profile Avatar": "个人头像",
  "Profile Name": "个人名称",
  "Enter your name": "输入您的名称",
  "Choose Photo": "选择照片",
  "Reset to Default": "重置为默认",
  "Supported formats: PNG, JPG, GIF. Max file size: 5MB.": "支持格式：PNG、JPG、GIF。文件大小限制：5MB。",
  "AI Tools": "AI 工具",
  "Models Config": "模型配置",
  "Skills Registry": "技能注册表",
  "MCP Server Hub": "MCP 服务网关",
  "Appearance": "外观配置",
  "Feature under active development": "功能正在积极开发中",
  "Active Palette Scheme:": "活跃配色方案:",
  "Active Theme": "活跃 主题",
  "Updates all buttons, panels, background layout variables, and typography states.": "刷新工作空间界面各布局组件、按钮面板及排版颜色状态。",
  "Customize the developer workspace environment with cohesive colors, borders, shadows, and eye-friendly presets.": "定制开发工作空间环境，包含协调的色彩、边框、阴影和对眼部友好的预设。",
  "Workspace Theme Configurator": "工作空间 主题配置器",

  // Model Config page
  "AI Workspace Models": "AI 模型中心",
  "Monitor, connect, and configure Large Language Models for active agent execution, reasoning logic, and prompt engineering.": "监视、连接和配置大语言模型，用于智能体执行、推理逻辑和提示词工程。",
  "Add External Model Provider": "添加外部 模型提供商",
  "Integration Hub": "集成中心",
  "Connect External Model Provider": "连接外部 模型提供商",
  "Model Name / Identifier": "模型标识符",
  "Provider Platform": "提供商平台",
  "Local Ollama Integration Guide": "本地 Ollama 集成指南",
  "Then run your model, for example:": "然后运行您的模型，例如：",
  "Custom Provider Name": "自定义提供商名称",
  "API Endpoint URL (Optional)": "API 端点 URL (可选)",
  "API Key / Credentials (Optional)": "凭据 (可选)",
  "Context Window Spec": "上下文窗口规格",
  "Default Temperature": "默认 Temperature温度",
  "Model Notes / Purpose": "模型备注与用途",
  "Save & Connect Model": "保存并连接 模型",
  "Cancel": "取消",
  "Configured & Connected Models": "已配置与已连接的 模型",
  "Installed": "已安装",
  "Active LLM Orchestrator:": "活跃 LLM Orchestrator大模型编排器:",
  "PROVIDER SYNCED": "提供方已同步",
  "Activate Mode": "激活 模型",

  // Chat placeholders / messages
  "Note: These settings only apply to the built-in Clutch Agent and MCP tools, and do not affect CLI Agents (such as Claude Code).": "提示：此权限模式仅适用于内置 Clutch 智能体与 MCP 工具，不影响 CLI 智能体（如 Claude Code）。",
  "@Agent your feedback (Hybrid) — auto-continues downstream; Stop to pause": "@Agent 反馈修改意见（Hybrid）— 精修后自动继续；可先停止再改",
  "Ask @Builder, @Orchestrator or trigger @Workflow...": "咨询 @Builder、@Orchestrator 或触发 @Workflow…",
  "Ask your AI Agent anything...": "向 AI 智能体提问…",
  "View execution details": "查看底层执行细节",
  "Shell command": "Shell 命令",
  "System prompt": "系统提示词",
  "Boundary marker": "边界标记",
  "Raw shell output": "原始 Shell 输出",
  "No structured execution details were captured for this turn.": "本轮未捕获结构化执行细节",
  "sections": "项",
  "Expand": "展开",
  "Collapse": "收起",
  "Run Workflow": "运行工作流",
  "Run SOP": "运行 SOP",
  "Start a supervised session": "开始新的监督会话",
  "Select a workspace and start a workflow, or type an instruction below. Clutch will orchestrate Builder / Evaluator and ask for your approval when needed.": "选择工作区并启动工作流，或直接在下方输入指令。Clutch 会编排 Builder/Evaluator，并在需要时请你审批。",
  "Start a single agent session": "开始单智能体会话",
  "Select a workspace and type an instruction below to chat with the agent directly.": "选择工作区并在下方输入指令，直接与智能体进行对话。",
  "Authorize workspace": "授权工作区",
  "Choose workflow template": "选择工作流模板",
  "Create Flow": "创建工作流",
  "Add Node": "添加节点",
  "Save Flow": "保存工作流",
  "Saving...": "保存中…",
  "Save Node": "保存节点",
  "Selected for chat": "已选中 · 用于 Chat",
  "No workflows yet": "暂无工作流",
  "Manage workflows...": "管理工作流...",
  "Manage models...": "管理模型...",
  "Manage agents...": "管理 Agent...",
  "No models configured": "暂无已配置模型",
  "View workflow": "查看工作流",
  "Edit workflow": "编辑工作流",
  "Edit Workflow": "编辑工作流",
  "Create New Workflow": "创建新工作流",
  "Delete workflow": "删除工作流",
  "Empty workflow — click Add Node to begin": "空工作流 — 点击 Add Node 开始编排",
  "Describe what you want this workflow to do...": "描述你希望此工作流完成的任务…",
  "Clear": "清除",
  "Workflow running": "工作流运行中",
  "Receiving sidecar events": "监督台正在接收 Sidecar 事件…",
  "Human gate hint": "检查未通过或需要人工确认，请选择下一步操作。",
  "Retry instructions placeholder": "附加指令，例如 \"跳过语法检查直接打包\"",
  "No active workflow overview": "暂无运行中的工作流。启动模板或发送指令后，这里会显示 Token 统计与 Flow 进度。",
  "No session activity yet": "开始与 Agent 对话后，这里会显示会话状态与 Token 统计。",
  "Workflow step execution": "工作流步骤执行",
  "Workflow steps unavailable": "无法加载工作流步骤定义。",
  "Workflow selected — send a message to start": "已选择工作流 — 发送消息即可启动",
  "Uncommitted changes": "未提交变更",
  "No uncommitted changes": "暂无未提交变更。",
  "Terminal logs": "终端日志",
  "Authorize workspace files hint": "请先在侧栏添加项目文件夹，或点击 Authorize workspace。",
  "Workspace folder empty": "工作区为空。",
  "No terminal logs yet": "暂无日志。启动工作流后 Sidecar 输出会显示在这里。",
  "Session tokens accumulated": "本轮累计",
  "Select project folder": "选择项目根目录",
  "Add project folder": "添加项目文件夹",
  "New project group": "新建项目分组",
  "Filter projects": "筛选项目",
  "No projects in this group yet": "此分组下暂无项目",
  "No projects match your filter": "没有匹配筛选条件的项目",
  "No repositories yet. Use Add project folder or Authorize workspace to begin.": "尚无项目。请通过侧栏添加文件夹，或点击 Authorize workspace。",
  "New session": "新建会话",
  "Projects": "项目",
  "No sessions in this project yet": "此项目下暂无会话",
  "Saved workspace snapshot": "已保存工作环境快照",
  "Continue previous work": "可继续上次工作",
  "Select a project before starting a conversation.": "请先选择项目，再开始对话。",
  "Are you sure you want to remove this project from the list?": "确定要从列表中移除该项目吗？",
  "Are you sure you want to permanently delete this session?": "确定要永久删除该会话吗？",
  "Delete": "删除",
  "Delete project": "删除项目",
  "Delete session": "删除会话",
  "Enter group name...": "请输入分组名称...",
  "Confirm": "确认",
  "Reload": "重新加载",
  "Thinking...": "思考中...",
  "Clutch Agent": "Clutch 智能体",
  "Settings": "设置",
  "Default Group": "默认分组",
  "Move to Group": "移动至分组",
  "Rename Group": "重命名分组",
  "Delete Group": "删除分组",
  "Rename": "重命名",
  "Are you sure you want to delete this group?": "确定要删除该分组吗？",
  "Enter new group name...": "请输入新的分组名称...",

  // Header
  "Select workspace": "选择工作区",
  "Go Back": "返回",
  "Workspace": "工作空间",

  // General Settings Panel
  "Developer Profiles": "开发者角色配置",
  "Active Workspace Developer Profiles": "活跃工作空间开发者配置",
  "Create, switch, or customize roles with tailored system prompt instructions, memory logs, and API allowances.": "创建、切换或定制具有系统提示词、内存日志和 API 配额的角色。",
  "Switch Profile": "切换 角色",
  "ACTIVE PROFILE": "活跃 角色",
  "System Prompt / Directive": "系统 提示词指令",
  "Active Memory context": "活跃 内存上下文",
  "API Calls Allowance Limit": "API 调用次数限额",
  "Customize Active Instructions": "定制 System Prompt系统提示词指令",
  "Update Developer Settings": "更新开发者设置",
  "Save Custom Settings": "保存自定义 角色",

  // Agent Manager
  "AI Agents Registry": "AI 智能体注册表",
  "Orchestrate, edit, and launch autonomous specialized agent personas with custom tool allocations and constraints.": "编排、编辑和启动具有自定义 工具分配和约束的自治专业 智能体角色。",
  "Create Custom Agent": "创建自定义 智能体",
  "System Orchestrator Status: Active": "系统编排器状态: 活跃",
  "Active Agent Roles": "活跃 智能体角色",
  "Define and manage agents and system roles.": "定义与管理 智能体 及系统角色。",
  "Core Role Directive": "核心 指令/提示词",
  "Equipped Tools": "装备 工具",
  "Active Tasks Log": "活跃任务日志",
  "System Instruction Prompt": "系统指令 提示词",
  "Edit Agent Details": "编辑 智能体详情",
  "Add Custom Agent Profile": "添加 智能体属性",
  "Agent Name / Brand": "智能体名称",
  "Primary Purpose": "主要用途",
  "System Instructions prompt": "系统指令 提示词",
  "Associated LLM Model": "关联 LLM Model大模型",
  "Add Agent Persona": "新增 智能体",
  "Save Persona Settings": "保存 智能体设置",
  "Active Agent": "当前智能体",
  "Select an AI Agent before sending.": "发送前请先选择智能体。",
  "Select an AI Agent or a Workflow before sending.": "发送前请选择智能体或工作流。",
  "builtin": "系统内置",
  "Edit Persona": "编辑 智能体角色",
  "Delete Persona": "删除 智能体角色",

  // Workflow panel
  "Workflows Standard Operating Procedures": "工作流 SOP标准作业程序",
  "Define, monitor, and execute step-by-step pipeline runs using automated agent interactions, validations, and artifact commits.": "通过自动化的 智能体交互、验证和 交付物提交，定义、监控并执行分步 管道流工作流。",
  "Create Custom SOP": "创建自定义 Workflows SOP标准作业程序",
  "Total Flows Loaded": "已加载 工作流总数",
  "Flow status:": "工作流状态:",
  "Flow Tasks SOP Progress": "任务进度",
  "Run Active SOP": "执行活跃 SOP",
  "Running Flow SOP Execution...": "正在执行 SOP中...",
  "Workflow execution successfully finished!": "工作流 SOP 执行成功完毕！",
  "Select a flow sequence to inspect execution.": "选择一个 工作流序列来检查执行状态。",
  "Step Details": "步骤详情",
  "Target Persona / Agent": "目标智能体",
  "Mock Output Artifact": "交付成果物",
  "View Generated Flow Output": "查看生成的 SOP结果",
  "Execution JSON Format": "执行格式 JSON",
  "Edit complex flows (checks, approvals, branches, loops) here; schema will be verified by Sidecar before saving.": "复杂流程（检查节点、人工审批、条件分支、循环）请在此编辑；保存前会经 Sidecar 校验。",
  "Failed to load": "加载失败",
  "Cannot connect to Sidecar": "无法连接 Sidecar",
  "Copy": "副本",
  "Saved to local workflow directory": "已保存到本机工作流目录",
  "Failed to save": "保存失败",
  "Step 1": "第一步",
  "Fill task instructions here": "在此填写任务说明",
  "Finish": "完成",
  "Failed to create workflow": "创建工作流失败",
  "Are you sure you want to delete this workflow?": "确定删除此工作流？",
  "Failed to delete": "删除失败",
  "Save as copy": "另存为副本",
  "Loading...": "加载中…",
  "Built-in template (Read-only)": "内置模板 · 只读",
  "User Workflow": "用户工作流",
  "Canvas editable (Simple linear workflow)": "支持画布编辑（简单线性流程）",
  "JSON mode only (Includes check/approval/branch)": "仅 JSON 模式（含检查/审批/分支）",
  "Canvas": "画布",
  "Complex workflow: please edit in JSON mode": "复杂流程：请用 JSON 编辑",
  "Built-in template: please save as copy after editing": "内置模板：编辑后请「另存为副本」",
  "Request failed": "请求失败",
  "JSON must contain id, nodes, and edges fields": "JSON 必须包含 id、nodes、edges 字段",
  "Confirm stopping the current run? This will interrupt Builder/Evaluator execution.": "确认停止当前运行？此操作将中断 Builder执行。",
  "Next steps: select \"Bypass & Approve\", \"Reject & Redo\" below, or type instructions and click \"Retry\".": "下一步：在下方选择「Bypass & Approve」、「Reject & Redo」，或填写指令后 Retry。",


  // AI Tools page
  "AI Tools Registry & Sandbox": "AI 工具注册中心与沙箱",
  "Integrate, configure, and sand-box server-side functions and client APIs usable by connected agents for live task completion.": "集成、配置和沙盒化服务端 函数和客户端 API，供已连接的 智能体用于实时任务完成。",
  "Add Custom Tool Plugin": "添加自定义 工具插件",
  "Register New Tool Extension": "注册新 工具",
  "Tool Label": "工具标签",
  "Execution Hook": "执行 钩子",
  "Plugin Source Script": "插件 源码脚本",
  "Register Tool Plugin": "注册 工具",
  "Connected Tool Providers": "已连接的 工具提供方",
  "Developer sandbox execution test:": "开发者沙盒执行测试:",
  "Test Tool Execution": "测试 工具",
  "ACTIVE / ONLINE": "活跃上线",
  "SIMULATION OK": "模拟状态正常",
  "Active Sandbox Logs:": "活跃沙盒日志",

  // Skills registry page
  "Skills Library Index": "技能库索引",
  "Provision pre-defined behavior trees, domain patterns, and schema blueprints directly into agent contextual memory.": "直接将预定义的行为树、领域模式和 架构蓝图注入 智能体上下文 内存空间中。",
  "Add Domain Skill Capability": "添加领域 技能",
  "System Skills Loaded": "已加载系统 技能",
  "Register Skill Tree Extension": "注册 技能",
  "Skill Label / Name": "技能名称",
  "System Prompt Capability Overlay": "提示词叠加",
  "Inject Skill Override": "注入 技能",
  "Active Domain Skills": "活跃领域 技能",
  "Status": "状态",
  "LOADED / ONLINE": "已加载上线",

  // MCP Servers
  "Model Context Protocol Gateways": "Model Context Protocol (MCP) 服务网关",
  "Connect and manage secure remote contextual backends, SQL servers, filesystem sockets, and public API registries supporting the MCP protocol.": "连接并管理支持 MCP 协议的远程 上下文后端、SQL 数据库、文件系统套接字和公共 API 注册表。",
  "Add Remote MCP Hub Connecting Sockets": "连接远程 MCP 服务组",
  "Connected MCP Sockets": "已连接的 MCP 节点",
  "Open Connection Sockets": "打开连接节点",
  "Configure Remote MCP Server Node": "配置 MCP 节点",
  "Socket Hook Name": "节点钩子名称",
  "Transport Layer Mode": "传输层模式",
  "Endpoint Transport URL": "传输层 URL",
  "Register Node": "注册 MCP 节点",
  "ONLINE / ACTIVE": "在线活跃",
  "ACTIVE CONNECTION OK": "活跃连接正常",

  // Base Header
  "Single Agent": "单智能体",
  "Multi-Agent": "多智能体",
  "Workspace theme updated to:": "配色主题更新为:",
  "Active LLM Orchestrator": "活跃 LLM 编排器",

  // Theme presets
  "Pristine Light": "极简白",
  "Clean Hanken aesthetic with spacious negative spaces and absolute neutral shades.": "极简 Hanken 设计风格，配有宽敞的负空间和绝对纯净的自然色彩预设。",
  "Cyberpunk Neon": "赛博霓虹",
  "Vibrant high-contrast dark theme with fluorescent purple, cyan, pink accents, and absolute neon shadows.": "高饱和度对比的暗黑主题，配有荧光紫、青色、粉色点缀与霓虹灯阴影效果。",
  "Nordic Frost": "北欧冰霜",
  "Serene soft-blue cool theme inspired by cold scandinavian winter, slate cliffs, and pine forests.": "受北欧严冬、石板悬崖和松林启发的松绿与淡蓝色冰霜极简格调方案。",
  "Slate Charcoal": "石板深灰",
  "Ultra-professional eye-saving dark theme focused on graphite shades, subtle borders, and steel tones.": "超干练眼部友好的深灰墨黑方案，聚焦于石墨黑、细腻纤薄边框和冷钢色调设计。",
  "Terminal Green": "终端绿",
  "Vintage matrix-style monochrome retro aesthetic showcasing glowing emerald typography and pure terminal layouts.": "复古 Matrix 终端单色美学，展现发光祖母绿字符与纯粹极客命令行布局样式。",

  // Theme UI components
  "Active": "活跃启用",
  "Palette:": "配色:",
  "Background": "背景色",
  "Surface": "界面色",
  "Text color": "文字色",
  "Accent primary": "核心主调",
  "Select": "选择应用",
  "System": "系统",

  // Right panel & misc UI
  "Overview": "概览",
  "Files": "文件",
  "Flow": "流程",
  "Changes": "变更",
  "Terminal": "终端",
  "Choose workflow": "选择工作流",
  "Workflows SOP": "工作流 SOP",
  "workflow": "工作流",
  "workflow_id": "工作流 ID",
  "active_node": "当前节点",
  "active_agent": "当前智能体",
  "status": "状态",
  "instruction": "指令",
  "Collapse Panel": "收起面板",
  "Expand Panel": "展开面板",
  "Close Panel": "关闭面板",
  "Collapse Sidebar": "折叠侧栏",
  "Expand Sidebar": "展开侧栏",
  "Session Token Analytics": "会话 Token 统计",
  "Total Tokens": "Token 总计",
  "Estimated Cost": "预估费用",
  "Token Distribution": "Token 分布",
  "Input vs Output": "输入 vs 输出",
  "Input": "输入",
  "Output": "输出",
  "Workspace Folder Structure": "工作区文件夹结构",
  "Preview file": "预览文件",
  "Preview Full": "完整预览",
  "Project Files": "项目文件",
  "Workflow agents": "工作流智能体",
  "Skills / Commands": "技能 / 命令",
  "Remove workflow": "移除工作流",
  "Model is determined by the selected workflow": "模型由所选工作流决定",
  "Model is bound on this agent": "模型绑定于当前智能体",
  "Failed to switch model.": "切换模型失败。",
  "Failed to save workflow": "保存工作流失败",
  "Save": "保存",
  "Drag to chat": "拖到聊天框",
  "idle": "空闲",
  "running": "运行中",
  "refining": "精修中",
  "awaiting_human": "待审批",
  "passed": "通过",
  "failed": "失败",

  // Onboarding wizard (OSR-14)
  "Welcome to Clutch": "欢迎使用 Clutch",
  "Local AI multi-agent orchestration for developers — supervise workflows, not black boxes.": "面向开发者的本地 AI 多智能体编排 — 监督工作流，而非黑盒。",
  "Environment requirements": "环境要求",
  "macOS 14+ recommended": "推荐 macOS 14+",
  "Apple Silicon recommended for local models": "本地模型推荐 Apple Silicon",
  "~500 MB disk space for app data": "约 500 MB 磁盘空间用于应用数据",
  "Network required for cloud LLM providers": "云模型提供商需要网络连接",
  "Unsigned DMG: allow in System Settings if macOS blocks launch": "未签名 DMG：若 macOS 拦截启动，请在系统设置中允许",
  "Onboarding env legend": "✓ 已满足 · ⚠ 建议项未满足（可继续）· ℹ 视使用方式而定。仅 Sidecar 就绪后可继续。",
  "✓ Met  ·  ⚠ Recommendation (you can continue)  ·  ℹ Informational only": "✓ 已满足 · ⚠ 建议项（可继续）· ℹ 仅供参考",
  "Yellow items are recommendations only — not blockers. You can continue once Sidecar is ready.": "黄色项仅为建议，不会阻止继续；Sidecar 就绪后即可点 Continue。",
  "Your macOS version meets our recommendation.": "macOS 版本符合建议。",
  "Older macOS detected — you can still use Clutch, but it is less tested on this version.": "系统版本偏旧；可继续使用，但该版本未充分测试。",
  "Could not verify macOS version (common on recent Macs). macOS 14+ is recommended.": "无法自动确认系统版本（较新 Mac 上常见）；建议使用 macOS 14+。",
  "Apple Silicon — best experience for local models like Ollama.": "Apple Silicon，本地模型（如 Ollama）体验更佳。",
  "Intel Mac detected — local models may run slower; cloud models and CLI tools work normally.": "检测到 Intel 芯片；本地模型可能较慢，云模型与 CLI 可正常使用。",
  "Could not detect chip type. Local model speed depends on your hardware.": "无法确认芯片类型；本地模型速度因硬件而异。",
  "Enough storage available for app data.": "可用存储空间充足。",
  "Low storage — saving workspace or preferences may fail. Free up ~500 MB.": "存储空间可能不足；请腾出约 500 MB。",
  "Could not measure free disk space. Please keep ~500 MB available.": "无法精确检测磁盘；请保留约 500 MB 可用空间。",
  "Online — you can configure cloud LLM providers.": "已联网；可配置云模型。",
  "Offline or no internet — skip cloud models and use a local CLI instead.": "当前离线；可跳过云模型，改用本地 CLI。",
  "Network status unknown.": "网络状态未知。",
  "Clutch is running — Gatekeeper step passed.": "应用已成功启动。",
  "Install from Clutch.app. If macOS blocks launch, see INSTALL.md.": "请从 Clutch.app 安装；若被拦截见 INSTALL.md。",
  "Checking environment…": "正在检测环境…",
  "Onboarding env warnings footnote": "存在建议项未满足，你仍可继续；部分能力（如云模型或本地大模型）可能受限。",
  "Onboarding env macos ok": "macOS 版本符合建议。",
  "Onboarding env macos warn": "系统版本偏旧或非 macOS；可继续使用，但未充分测试。",
  "Onboarding env macos info": "无法自动确认系统版本；建议使用 macOS 14+。",
  "Onboarding env arch ok": "Apple Silicon，本地模型体验更佳。",
  "Onboarding env arch warn": "Intel 芯片；本地模型可能较慢，云模型与 CLI 仍可用。",
  "Onboarding env arch info": "无法确认芯片类型；本地模型性能因机器而异。",
  "Onboarding env disk ok": "可用存储空间充足。",
  "Onboarding env disk warn": "可用空间可能不足；保存工作区或配置时可能失败。",
  "Onboarding env disk info": "无法精确检测磁盘；请确保约 500 MB 可用空间。",
  "Onboarding env network ok": "已联网；可配置云模型提供商。",
  "Onboarding env network warn": "当前离线或网络不可用；可跳过云模型，改连本地 CLI。",
  "Onboarding env gatekeeper ok": "应用已成功启动。",
  "Onboarding env gatekeeper info": "请从 Clutch.app 安装并启动；若被拦截见 INSTALL.md。",
  "Waiting for Clutch sidecar…": "正在等待 Clutch Sidecar…",
  "Sidecar ready": "Sidecar 已就绪",
  "Sidecar not ready": "Sidecar 未就绪",
  "See INSTALL.md §8 for troubleshooting": "故障排除见 INSTALL.md 第 8 节",
  "Retry": "重试",
  "Continue": "继续",
  "Choose your workspace": "选择工作区",
  "Clutch reads and writes only inside the project folder you authorize.": "Clutch 仅在你授权的项目文件夹内读写。",
  "Use Clutch.app to complete first-time setup": "请使用 Clutch.app 完成首次设置",
  "Selected": "已选择",
  "Selecting…": "选择中…",
  "Workspace authorize failed": "工作区授权失败",
  "Connect a cloud model": "连接云模型",
  "Onboarding models skip hint": "可跳过此步，稍后在设置中配置；若不用云模型，请在下一步连接本地 CLI。",
  "Onboarding keychain note": "API 密钥存储在 macOS 钥匙串，不会写入 models.json。",
  "Enter an API key for this provider": "请为此提供商输入 API Key",
  "No model available for this provider yet": "此提供商暂无可用模型",
  "Could not save model configuration": "无法保存模型配置",
  "Model connection verified": "模型连接已验证",
  "Test connection": "测试连接",
  "Skip for now": "暂时跳过",
  "Connect local CLI tools": "连接本地 CLI 工具",
  "Onboarding tools skip hint": "若上一步已验证模型，可跳过；否则请连接至少一个 CLI。",
  "If you verified a cloud model above, you can skip; otherwise connect at least one CLI.": "若上一步已验证模型，可跳过；否则请连接至少一个 CLI。",
  "Rescan": "重新扫描",
  "Scanning local toolchains…": "正在扫描本地工具链…",
  "Onboarding no cli installed": "尚未检测到已安装的 AI CLI。安装后点击重新扫描并连接。",
  "No AI command-line tools detected yet": "尚未检测到 AI 命令行工具",
  "Install at least one recommended tool below (e.g. Claude Code, Ollama, or Aider). After installing in Terminal, click Rescan, then Connect. If you configured a cloud model, you can skip this step after verifying it.": "请至少安装一个推荐工具（如 Claude Code、Ollama 或 Aider）。在终端安装完成后点击「重新扫描」，再点「连接」。若已配置云模型，验证通过后也可跳过此步。",
  "Run a command below in Terminal, then return here and click Rescan.": "在终端运行下方命令后，回到此页点击 Rescan。",
  "Recommended to install": "推荐安装",
  "More CLI options": "更多 CLI 选项",
  "Not installed": "未安装",
  "Show install guide": "查看安装指引",
  "Hide install guide": "收起安装指引",
  "Visit website": "访问官网",
  "Copy command": "复制命令",
  "Connected": "已连接",
  "Connect": "连接",
  "Onboarding agent created": "已创建 Agent「{name}」，完成向导后可直接使用",
  "Onboarding ollama no models": "请先启动 Ollama 并拉取模型，然后重新扫描",
  "Onboarding model or tools required": "请验证模型连接，或连接至少一个本地 CLI（二选一即可）",
  "Failed to connect tool": "连接工具失败",
  "Sidecar unavailable — start the orchestrator": "Sidecar 不可用 — 请启动 orchestrator",
  "Cannot reach Clutch sidecar": "无法连接 Clutch Sidecar",
  "Orchestrate your workflows (Flow)": "编排你的工作流（Flow）",
  "Workflows (Flow)": "工作流（Flow）",
  "Chain multiple Agents with a visual workflow.": "用可视化工作流串联多个 Agent。",
  "Where to find it": "入口",
  "Quick setup": "配置方法",
  "Create a new workflow (or pick a built-in template)": "新建 Workflow（或选内置模板）",
  "Drag nodes onto the canvas and connect them": "在画布上拖拽节点并连线",
  "Bind an AI Agent to each task node, then Save": "为每个 Agent 任务节点绑定 AI Agent → 保存",
  "In chat: Workflow menu → select your flow → send a task": "聊天页：底部 Workflow 菜单 → 选中 Flow → 发送任务",
  "Single-Agent chat does not need a Flow.": "单 Agent 聊天无需 Flow。",
  "Onboarding flow tagline": "用可视化步骤串联多个 Agent。",
  "Onboarding flow subtitle": "Clutch 用可视化 SOP 串联多个 Agent；可用内置模板，也可自己拖拽编排。",
  "Onboarding flow sidebar title": "侧栏 · Workflows SOP",
  "Onboarding flow sidebar body": "打开画布，新建或编辑 Flow",
  "Onboarding flow footer title": "底部栏 · Workflow 菜单",
  "Onboarding flow footer body": "在聊天前选中要运行的 Flow",
  "Onboarding flow panel title": "右侧面板 · Flow 标签",
  "Onboarding flow panel body": "运行中查看步骤进度与高亮",
  "Onboarding flow step 1": "侧栏点 Workflows SOP → 选内置模板或新建 → 拖拽节点 → 保存",
  "Onboarding flow step 2": "回聊天页，底部 Workflow 下拉选中刚保存的 Flow → 输入任务发送",
  "Onboarding flow step 3": "Agent 任务节点绑定你在 Tools 步创建/已有的 AI Agent",
  "Onboarding flow footnote": "完成向导后可在侧栏 Workflows SOP 打开；单 Agent 聊天无需 Flow。",
  "Permission modes (preview)": "权限模式（预览）",
  "Permission mode": "权限模式",
  "Only Ask before changes is active today. Other modes are still in development.": "当前仅「变更前询问」可用，其余模式仍在开发中。",
  "In development": "开发中",
  "Permission onboarding footnote": "本地 CLI 可能仍会较少确认即执行；此处无需选择，完成向导后可在设置查看。",
  "Onboarding permissions intro": "权限模式将用于 MCP / 工具调用的人机门控（规划中）。",
  "Current default": "当前默认",
  "Coming soon": "即将推出",
  "Ask before changes": "变更前询问",
  "Ask before file changes.": "文件变更前询问。",
  "Edit automatically": "自动编辑",
  "Edit files automatically.": "自动编辑文件。",
  "Plan mode": "计划模式",
  "Plan before editing.": "编辑前先计划。",
  "Full access": "完全访问",
  "Run with fewer confirmations.": "减少确认步骤运行。",
  "Onboarding permissions mcp note": "Permission 模式将用于 MCP / 工具调用的人机门控（规划中）。",
  "Onboarding permissions cli note": "本地 CLI（如 Claude Code）目前仍可能自动执行，详见 README 安全与 CLI 权限。",
  "Onboarding permissions future note": "完整可选能力将在后续版本开放，无需在此步选择。",
  "Ready to launch": "准备启动",
  "Review your setup, then open the workspace.": "确认配置后进入工作区。",
  "Active model": "活跃模型",
  "Not configured (CLI path)": "未配置（CLI 路径）",
  "Execution path": "执行路径",
  "Both cloud model and local CLI": "云模型 + 本地 CLI",
  "Cloud model": "云模型",
  "Local CLI": "本地 CLI",
  "Default ask (read-only)": "默认 ask（只读）",
  "Default agent": "默认 Agent",
  "Keys stored in macOS Keychain": "密钥存储在 macOS 钥匙串",
  "Keys stored securely (Keychain on macOS)": "密钥安全存储（macOS 上使用钥匙串）",
  "Full permission mode selection coming soon": "完整权限模式选择即将推出",
  "Launch workspace →": "启动工作区 →",
  "Launching…": "启动中…",
  "Could not finish onboarding": "无法完成向导",
  "Back": "返回",
  "Hide": "隐藏",
  "Show": "显示",
};


export const translateRunStatus = (status: string, language: Language): string => {
  if (language === 'en') return status;
  const key = status.trim().toLowerCase();
  return zhTranslations[key] ?? status;
};

// Fallback translator for keys not in the dictionary.
export const translateText = (text: string, language: Language): string => {
  if (language === 'en') return text;

  const trimmed = text.trim();
  if (zhTranslations[trimmed]) {
    return zhTranslations[trimmed];
  }

  const termsMap: Array<{ regex: RegExp; replacement: string }> = [
    { regex: /\bMulti-Agent\b/gi, replacement: '多智能体' },
    { regex: /\bSingle-Agent\b/gi, replacement: '单智能体' },
    { regex: /\bWorkflows?\b/gi, replacement: '工作流' },
    { regex: /\bAgents?\b/gi, replacement: '智能体' },
    { regex: /\bModels?\b/gi, replacement: '模型' },
    { regex: /\bPrompts?\b/gi, replacement: '提示词' },
    { regex: /\bSkills?\b/gi, replacement: '技能' },
    { regex: /\bTools?\b/gi, replacement: '工具' },
  ];

  let result = trimmed;
  for (const { regex, replacement } of termsMap) {
    result = result.replace(regex, replacement);
  }
  return result;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('workspace_lang');
    return (saved === 'zh' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    void fetchLanguagePreference()
      .then((lang) => {
        setLanguageState(lang);
        localStorage.setItem('workspace_lang', lang);
      })
      .catch(() => {});
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('workspace_lang', lang);
    void saveLanguagePreference(lang).catch(() => {});
  };

  const t = (key: string): string => {
    return translateText(key, language);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
