"""Route image-generation models to the correct adapter backend."""

from __future__ import annotations

import base64
import re
import uuid
import urllib.request
from collections.abc import Callable
from typing import Any

from src.artifact_layout import CLUTCH_IMAGE_DIR
from src.llm.router import ModelSpec
from src.preferences_storage import tr

GenerateFn = Callable[..., dict[str, Any]]
VerifyFn = Callable[..., None]
_FETCH_TIMEOUT_SEC = 60.0


def is_image_model(spec: ModelSpec) -> bool:
    return spec.model_kind == "image"


def resolve_image_backend(spec: ModelSpec) -> str:
    if spec.image_backend:
        return spec.image_backend
    base = spec.base_url.lower()
    if "agnes-ai.com" in base:
        return "agnes"
    return "openai_images"


def _generator_for(backend: str) -> GenerateFn:
    if backend == "agnes":
        from src.adapters.agnes_image_adapter import generate_agnes_image

        return generate_agnes_image
    if backend == "openai_images":
        from src.adapters.openai_images_adapter import generate_openai_image

        return generate_openai_image
    raise RuntimeError(f"Unsupported image backend: {backend!r}")


def _verifier_for(backend: str) -> VerifyFn:
    if backend == "agnes":
        from src.adapters.agnes_image_adapter import verify_agnes_image_connection

        return verify_agnes_image_connection
    if backend == "openai_images":
        from src.adapters.openai_images_adapter import verify_openai_image_connection

        return verify_openai_image_connection
    raise RuntimeError(f"Unsupported image backend: {backend!r}")


def _fetch_url_as_b64(url: str) -> str:
    with urllib.request.urlopen(url, timeout=_FETCH_TIMEOUT_SEC) as resp:
        payload = resp.read()
        headers = resp.headers
        if hasattr(headers, "get_content_type"):
            content_type = headers.get_content_type()
        else:
            content_type = headers.get("Content-Type", "image/png")
        content_type = (content_type or "image/png").split(";")[0].strip()
    if not payload:
        raise RuntimeError("Image URL returned empty body")
    return f"data:{content_type};base64,{base64.b64encode(payload).decode('ascii')}"


def _ensure_inline_image(result: dict[str, Any]) -> dict[str, Any]:
    """Providers often return CDN URLs even when base64 was requested — fetch for Tauri CSP."""
    if str(result.get("b64_json") or "").strip():
        return result
    url = str(result.get("url") or "").strip()
    if not url:
        return result
    try:
        return {**result, "b64_json": _fetch_url_as_b64(url)}
    except Exception:
        return result


def generate_image_for_model(
    spec: ModelSpec,
    prompt: str,
    *,
    api_key: str,
    on_log: Callable[[str], None] | None = None,
    response_format: str = "b64_json",
) -> dict[str, Any]:
    """Generate an image. Defaults to base64 so Tauri WebView CSP (data:) can render it."""
    backend = resolve_image_backend(spec)
    result = _generator_for(backend)(
        prompt,
        api_key=api_key,
        model=spec.api_model,
        base_url=spec.base_url,
        on_log=on_log,
        response_format=response_format,
    )
    if response_format == "b64_json":
        result = _ensure_inline_image(result)
    return result


def verify_image_model_connection(
    spec: ModelSpec,
    *,
    api_key: str,
) -> None:
    backend = resolve_image_backend(spec)
    _verifier_for(backend)(api_key=api_key, model=spec.api_model, base_url=spec.base_url)


def persist_generated_image(result: dict[str, Any], *, filename_stem: str | None = None) -> dict[str, Any]:
    """Write generated bytes under `.clutch/generated/images/` (same idea as videos)."""
    if str(result.get("local_media_path") or "").strip():
        return result
    b64_json = str(result.get("b64_json") or "").strip()
    raw_b64 = b64_json
    mime = "image/png"
    if b64_json.startswith("data:"):
        match = re.match(r"^data:([^;]+);base64,(.+)$", b64_json, re.DOTALL)
        if match:
            mime = match.group(1).strip() or mime
            raw_b64 = match.group(2).strip()
    if not raw_b64:
        return result
    try:
        from src.workspace import get_workspace, require_workspace, resolve_allowed_path

        ws = get_workspace()
        if not ws or not str(ws.get("workspace_path", "")).strip():
            return result
        require_workspace()
        ext = ".png"
        if "jpeg" in mime or "jpg" in mime:
            ext = ".jpg"
        elif "webp" in mime:
            ext = ".webp"
        elif "gif" in mime:
            ext = ".gif"
        stem = re.sub(r"[^a-zA-Z0-9_-]+", "-", (filename_stem or "").strip())[:48].strip("-")
        name = f"{stem or 'image'}_{uuid.uuid4().hex[:10]}{ext}"
        rel = f"{CLUTCH_IMAGE_DIR}/{name}"
        target = resolve_allowed_path(rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(base64.b64decode(raw_b64))
        return {**result, "local_media_path": rel, "b64_json": b64_json or f"data:{mime};base64,{raw_b64}"}
    except Exception:
        return result


def format_image_reply(result: dict[str, Any]) -> str:
    """Prefer inline base64 so Tauri WebView CSP (data:) can render without remote img-src."""
    persisted = persist_generated_image(result)
    b64_json = str(persisted.get("b64_json") or "").strip()
    image_url = str(persisted.get("url") or "").strip()
    local = str(persisted.get("local_media_path") or "").strip()
    label = tr("Generated image", "生成的图片")
    if b64_json:
        data_uri = b64_json if b64_json.startswith("data:") else f"data:image/png;base64,{b64_json}"
        body = f"![{label}]({data_uri})"
        if local:
            body += f"\n\n{tr('Saved to', '已保存至')} `{local}`"
        return body
    if image_url:
        body = f"![{label}]({image_url})"
        if local:
            body += f"\n\n{tr('Saved to', '已保存至')} `{local}`"
        return body
    return tr(
        "Image generation completed but no image was returned.",
        "图片生成已完成，但未返回图像数据。",
    )


def resolve_configured_image_model() -> tuple[ModelSpec, str] | None:
    """Pick the first image model that has a configured API key."""
    try:
        from src.models_config import get_router

        router = get_router()
        preferred = ("agnes-image-2.1-flash",)
        ordered = list(router.list_models())
        ordered.sort(key=lambda s: (0 if s.id in preferred else 1, s.id))
        for spec in ordered:
            if getattr(spec, "model_kind", "chat") != "image":
                continue
            key = router.get_api_key(spec.provider_id)
            if key and str(key).strip():
                return spec, str(key).strip()
    except Exception:
        return None
    return None
